version: '3.1'
services:
  app:
    container_name: abacc-adelaide
    image: abacc-adelaide
    build: ./
    ports:
      - "4040:4040"
    depends_on:
      - postdb
  postdb:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=abacc

